---
abstract: 'Interface to search CPAN module author.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  HTML::Entities: 1.35
  HTTP::Request: 1.40
  LWP::UserAgent: 2.33
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Search-Author
provides:
  CPAN::Search::Author:
    file: lib/CPAN/Search/Author.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
